version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: fastapi_container
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql+pymysql://user:password@mysql:3306/testdb
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload


  frontend:
    build: ./frontend
    container_name: nextjs_container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app        # ← コード変更を即反映！
      - /app/node_modules      # ← node_modules は除外しておく
    working_dir: /app
    command: npm run dev       # ← Next.jsを開発モードで起動！
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000


volumes:
  mysql_data:
