version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"

  backend:
    image: wildcats9999.azurecr.io/backend:latest
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mysql:3306/testdb
    ports:
      - "8000:8000"

  frontend:
    image: wildcats9999.azurecr.io/frontend:latest
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://backend-container.wonderfulbeach-7a1caae1.japaneast.azurecontainerapps.io
    ports:
      - "3000:3000"
