"""タグモデルとポストタグ関連テーブルを追加

Revision ID: d3cc0421a4ff
Revises: 63b3a915d2ff
Create Date: 2025-04-14 13:11:28.166525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3cc0421a4ff'
down_revision: Union[str, None] = '63b3a915d2ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
